-- ============================================================
-- supabase-fix2.sql · 修复管理面板 structure of query 报错
-- 幂等可重复执行。运行后: 重新登录站点 → 打开管理面板
-- ============================================================

-- ① profiles 表结构对齐 (缺列补建, 幂等)
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS username TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS display_name TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS github_username TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS github_avatar_url TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS website TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'user';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS account_status TEXT NOT NULL DEFAULT 'active';


-- ② 缺失表补建 (仅建不存在的表)

CREATE TABLE IF NOT EXISTS public.content_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  post_path TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  author_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'draft',
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  review_reason TEXT,
  reviewed_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.content_versions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  content_item_id UUID NOT NULL REFERENCES public.content_items(id) ON DELETE CASCADE,
  version_number INTEGER NOT NULL,
  source_markdown TEXT NOT NULL,
  checksum TEXT NOT NULL,
  created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (content_item_id, version_number)
);

-- 表 uploads 定义未找到

CREATE TABLE IF NOT EXISTS public.audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.security_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL,
  severity TEXT NOT NULL DEFAULT 'info',
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  recipient_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  notification_type TEXT NOT NULL,
  title TEXT NOT NULL,
  body TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ③ 核心函数重建 (CREATE OR REPLACE, 修复结构不匹配)

CREATE OR REPLACE FUNCTION public.has_any_role(required_roles TEXT[])
RETURNS BOOLEAN
SECURITY DEFINER
STABLE
SET search_path = public, pg_temp
LANGUAGE sql
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = auth.uid()
      AND account_status = 'active'
      AND role = ANY(required_roles)
  );
$$;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
SECURITY DEFINER
STABLE
SET search_path = public, pg_temp
LANGUAGE sql
AS $$
  SELECT public.has_any_role(ARRAY['superadmin']);
$$;

CREATE OR REPLACE FUNCTION public.get_my_profile()
RETURNS TABLE (
  id UUID,
  username TEXT,
  display_name TEXT,
  bio TEXT,
  avatar_url TEXT,
  github_username TEXT,
  github_avatar_url TEXT,
  website TEXT,
  role TEXT,
  account_status TEXT,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ
)
SECURITY DEFINER
STABLE
SET search_path = public, pg_temp
LANGUAGE sql
AS $$
  SELECT p.id, p.username, p.display_name, p.bio, p.avatar_url,
         p.github_username, p.github_avatar_url, p.website, p.role,
         p.account_status, p.created_at, p.updated_at
  FROM public.profiles p
  WHERE p.id = auth.uid();
$$;

CREATE OR REPLACE FUNCTION public.try_claim_primary_superadmin()
RETURNS BOOLEAN
SECURITY DEFINER
SET search_path = public, pg_temp
LANGUAGE plpgsql
AS $$
DECLARE
  primary_profile_id UUID := auth.uid();
  github_login TEXT;
BEGIN
  IF primary_profile_id IS NULL THEN
    RETURN FALSE;
  END IF;

  SELECT lower(COALESCE(
    i.identity_data->>'user_name',
    i.identity_data->>'login',
    i.identity_data->>'preferred_username'
  ))
  INTO github_login
  FROM auth.identities i
  WHERE i.user_id = primary_profile_id
    AND i.provider = 'github'
  ORDER BY i.created_at
  LIMIT 1;

  IF github_login IS DISTINCT FROM 'levia808' THEN
    RETURN FALSE;
  END IF;

  UPDATE public.profiles
  SET role = 'user'
  WHERE id <> primary_profile_id
    AND role IN ('admin', 'superadmin');

  UPDATE public.profiles
  SET role = 'superadmin',
      account_status = 'active'
  WHERE id = primary_profile_id;

  RETURN FOUND;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_dashboard_stats()
RETURNS JSONB
SECURITY DEFINER
STABLE
SET search_path = public, pg_temp
LANGUAGE plpgsql
AS $$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Administrator access required' USING ERRCODE = '42501';
  END IF;
  RETURN jsonb_build_object(
    'total_users', (SELECT COUNT(*) FROM public.profiles),
    'active_users', (SELECT COUNT(*) FROM public.profiles WHERE account_status = 'active'),
    'total_comments', (SELECT COUNT(*) FROM public.comments),
    'pending_comments', (SELECT COUNT(*) FROM public.comments WHERE moderation_status = 'pending'),
    'open_reports', (SELECT COUNT(*) FROM public.comment_reports WHERE status = 'open'),
    'published_content', (SELECT COUNT(*) FROM public.content_items WHERE status = 'published'),
    'pending_content', (SELECT COUNT(*) FROM public.content_items WHERE status = 'pending_review')
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_list_users()
RETURNS TABLE (
  id UUID,
  email TEXT,
  username TEXT,
  display_name TEXT,
  avatar_url TEXT,
  github_username TEXT,
  role TEXT,
  account_status TEXT,
  created_at TIMESTAMPTZ,
  last_sign_in_at TIMESTAMPTZ
)
SECURITY DEFINER
STABLE
SET search_path = public, pg_temp
LANGUAGE plpgsql
AS $$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Administrator access required' USING ERRCODE = '42501';
  END IF;
  RETURN QUERY
  SELECT p.id, u.email, p.username, p.display_name, p.avatar_url,
         p.github_username, p.role, p.account_status, p.created_at, u.last_sign_in_at
  FROM public.profiles p
  LEFT JOIN auth.users u ON u.id = p.id
  ORDER BY p.created_at DESC;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_list_comments(p_status TEXT DEFAULT NULL)
RETURNS TABLE (
  id BIGINT,
  post_path TEXT,
  content TEXT,
  moderation_status TEXT,
  moderation_reason TEXT,
  created_at TIMESTAMPTZ,
  user_id UUID,
  display_name TEXT,
  username TEXT
)
SECURITY DEFINER
STABLE
SET search_path = public, pg_temp
LANGUAGE plpgsql
AS $$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Administrator access required' USING ERRCODE = '42501';
  END IF;
  RETURN QUERY
  SELECT c.id, c.post_path, c.content, c.moderation_status, c.moderation_reason,
         c.created_at, c.user_id, p.display_name, p.username
  FROM public.comments c
  LEFT JOIN public.profiles p ON p.id = c.user_id
  WHERE p_status IS NULL OR c.moderation_status = p_status
  ORDER BY c.created_at DESC;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_list_reports(p_status TEXT DEFAULT 'open')
RETURNS TABLE (
  id BIGINT,
  comment_id BIGINT,
  reason TEXT,
  status TEXT,
  created_at TIMESTAMPTZ,
  reporter_id UUID,
  reporter_name TEXT,
  comment_content TEXT,
  comment_path TEXT
)
SECURITY DEFINER
STABLE
SET search_path = public, pg_temp
LANGUAGE plpgsql
AS $$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Administrator access required' USING ERRCODE = '42501';
  END IF;
  RETURN QUERY
  SELECT r.id, r.comment_id, r.reason, r.status, r.created_at, r.reporter_id,
         COALESCE(rp.display_name, rp.username), c.content, c.post_path
  FROM public.comment_reports r
  JOIN public.comments c ON c.id = r.comment_id
  LEFT JOIN public.profiles rp ON rp.id = r.reporter_id
  WHERE p_status IS NULL OR r.status = p_status
  ORDER BY r.created_at DESC;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_list_content(p_status TEXT DEFAULT NULL)
RETURNS SETOF public.content_items
SECURITY DEFINER
STABLE
SET search_path = public, pg_temp
LANGUAGE plpgsql
AS $$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Administrator access required' USING ERRCODE = '42501';
  END IF;
  RETURN QUERY
  SELECT c.*
  FROM public.content_items c
  WHERE p_status IS NULL OR c.status = p_status
  ORDER BY c.updated_at DESC;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_list_media()
RETURNS SETOF public.media_assets
SECURITY DEFINER
STABLE
SET search_path = public, pg_temp
LANGUAGE plpgsql
AS $$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Administrator access required' USING ERRCODE = '42501';
  END IF;
  RETURN QUERY
  SELECT * FROM public.media_assets
  WHERE deleted_at IS NULL
  ORDER BY created_at DESC;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_list_audit_logs(p_limit INTEGER DEFAULT 100)
RETURNS SETOF public.audit_logs
SECURITY DEFINER
STABLE
SET search_path = public, pg_temp
LANGUAGE plpgsql
AS $$
BEGIN
  IF NOT public.is_superadmin() THEN
    RAISE EXCEPTION 'Superadmin access required' USING ERRCODE = '42501';
  END IF;
  RETURN QUERY
  SELECT * FROM public.audit_logs ORDER BY created_at DESC LIMIT LEAST(GREATEST(p_limit, 1), 500);
END;
$$;

CREATE OR REPLACE FUNCTION public.moderate_comment(
  p_comment_id BIGINT,
  p_status TEXT,
  p_reason TEXT DEFAULT NULL
)
RETURNS public.comments
SECURITY DEFINER
SET search_path = public, pg_temp
LANGUAGE plpgsql
AS $$
DECLARE
  updated_comment public.comments;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Administrator access required' USING ERRCODE = '42501';
  END IF;
  IF p_status NOT IN ('pending', 'approved', 'rejected', 'hidden') THEN
    RAISE EXCEPTION 'Invalid moderation status' USING ERRCODE = '22023';
  END IF;
  UPDATE public.comments
  SET moderation_status = p_status,
      moderation_reason = NULLIF(trim(p_reason), ''),
      moderated_by = auth.uid(),
      moderated_at = NOW(),
      deleted_at = CASE WHEN p_status = 'hidden' THEN COALESCE(deleted_at, NOW()) ELSE NULL END
  WHERE id = p_comment_id
  RETURNING * INTO updated_comment;
  IF updated_comment.id IS NULL THEN
    RAISE EXCEPTION 'Comment not found' USING ERRCODE = 'P0002';
  END IF;
  UPDATE public.moderation_queue
  SET status = CASE WHEN p_status IN ('approved', 'rejected', 'hidden') THEN 'resolved' ELSE 'in_review' END,
      updated_at = NOW()
  WHERE comment_id = p_comment_id AND status IN ('pending', 'in_review');
  UPDATE public.comment_reports
  SET status = CASE WHEN p_status IN ('rejected', 'hidden') THEN 'actioned' ELSE 'dismissed' END,
      resolved_by = auth.uid(),
      resolved_at = NOW()
  WHERE comment_id = p_comment_id AND status = 'open';
  IF updated_comment.user_id <> auth.uid() THEN
    PERFORM public.create_notification(
      updated_comment.user_id,
      'comment.moderated',
      'Comment moderation result',
      CASE p_status
        WHEN 'approved' THEN 'Your comment was approved.'
        WHEN 'rejected' THEN 'Your comment was rejected.'
        WHEN 'hidden' THEN 'Your comment was hidden.'
        ELSE 'Your comment status was updated.'
      END,
      jsonb_build_object('comment_id', p_comment_id, 'status', p_status)
    );
  END IF;
  PERFORM public.write_audit_log(
    'comment.moderate',
    'comment',
    p_comment_id::TEXT,
    jsonb_build_object('status', p_status, 'reason', p_reason)
  );
  RETURN updated_comment;
END;
$$;

CREATE OR REPLACE FUNCTION public.report_comment(p_comment_id BIGINT, p_reason TEXT)
RETURNS BOOLEAN
SECURITY DEFINER
SET search_path = public, pg_temp
LANGUAGE plpgsql
AS $$
DECLARE
  comment_owner UUID;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'You must be signed in to report a comment' USING ERRCODE = '42501';
  END IF;
  SELECT user_id INTO comment_owner FROM public.comments WHERE id = p_comment_id;
  IF comment_owner IS NULL THEN
    RAISE EXCEPTION 'Comment not found' USING ERRCODE = 'P0002';
  END IF;
  IF comment_owner = auth.uid() THEN
    RAISE EXCEPTION 'You cannot report your own comment' USING ERRCODE = '22023';
  END IF;
  INSERT INTO public.comment_reports (comment_id, reporter_id, reason)
  VALUES (p_comment_id, auth.uid(), trim(p_reason))
  ON CONFLICT (comment_id, reporter_id) DO NOTHING;
  PERFORM public.write_audit_log('comment.report', 'comment', p_comment_id::TEXT,
    jsonb_build_object('reason', trim(p_reason)));
  RETURN TRUE;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_update_account_status(
  p_user_id UUID,
  p_status TEXT
)
RETURNS public.profiles
SECURITY DEFINER
SET search_path = public, pg_temp
LANGUAGE plpgsql
AS $$
DECLARE
  updated_profile public.profiles;
  target_role TEXT;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Administrator access required' USING ERRCODE = '42501';
  END IF;
  IF p_status NOT IN ('active', 'suspended', 'deleted') THEN
    RAISE EXCEPTION 'Invalid account status' USING ERRCODE = '22023';
  END IF;
  SELECT role INTO target_role FROM public.profiles WHERE id = p_user_id;
  IF target_role IS NULL THEN
    RAISE EXCEPTION 'User not found' USING ERRCODE = 'P0002';
  END IF;
  IF target_role = 'superadmin' AND NOT public.is_superadmin() THEN
    RAISE EXCEPTION 'Only a superadmin can change a superadmin account' USING ERRCODE = '42501';
  END IF;
  UPDATE public.profiles
  SET account_status = p_status
  WHERE id = p_user_id
  RETURNING * INTO updated_profile;
  PERFORM public.write_audit_log(
    'user.status.update',
    'profile',
    p_user_id::TEXT,
    jsonb_build_object('status', p_status)
  );
  RETURN updated_profile;
END;
$$;

CREATE OR REPLACE FUNCTION public.superadmin_update_role(
  p_user_id UUID,
  p_role TEXT
)
RETURNS public.profiles
SECURITY DEFINER
SET search_path = public, pg_temp
LANGUAGE plpgsql
AS $$
DECLARE
  updated_profile public.profiles;
BEGIN
  IF NOT public.is_superadmin() THEN
    RAISE EXCEPTION 'Superadmin access required' USING ERRCODE = '42501';
  END IF;
  IF p_role NOT IN ('user', 'author', 'admin', 'superadmin') THEN
    RAISE EXCEPTION 'Invalid role' USING ERRCODE = '22023';
  END IF;
  UPDATE public.profiles SET role = p_role WHERE id = p_user_id RETURNING * INTO updated_profile;
  IF updated_profile.id IS NULL THEN
    RAISE EXCEPTION 'User not found' USING ERRCODE = 'P0002';
  END IF;
  PERFORM public.write_audit_log(
    'user.role.update',
    'profile',
    p_user_id::TEXT,
    jsonb_build_object('role', p_role)
  );
  RETURN updated_profile;
END;
$$;

CREATE OR REPLACE FUNCTION public.register_media_asset(
  p_storage_path TEXT,
  p_file_name TEXT,
  p_mime_type TEXT,
  p_size_bytes BIGINT,
  p_public_url TEXT,
  p_metadata JSONB DEFAULT '{}'::jsonb
)
RETURNS public.media_assets
SECURITY DEFINER
SET search_path = public, pg_temp
LANGUAGE plpgsql
AS $$
DECLARE
  asset public.media_assets;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Administrator access required' USING ERRCODE = '42501';
  END IF;
  IF p_mime_type NOT LIKE 'image/%' AND p_mime_type NOT LIKE 'video/%' AND p_mime_type NOT LIKE 'audio/%' THEN
    RAISE EXCEPTION 'Unsupported media type' USING ERRCODE = '22023';
  END IF;
  IF p_size_bytes <= 0 OR p_size_bytes > 104857600 THEN
    RAISE EXCEPTION 'Media file must be between 1 byte and 100 MB' USING ERRCODE = '22023';
  END IF;
  INSERT INTO public.media_assets (
    storage_path, file_name, mime_type, size_bytes, public_url, uploaded_by, metadata
  )
  VALUES (
    trim(p_storage_path), trim(p_file_name), lower(trim(p_mime_type)),
    p_size_bytes, trim(p_public_url), auth.uid(), COALESCE(p_metadata, '{}'::jsonb)
  )
  ON CONFLICT (storage_path) DO UPDATE
  SET file_name = EXCLUDED.file_name,
      mime_type = EXCLUDED.mime_type,
      size_bytes = EXCLUDED.size_bytes,
      public_url = EXCLUDED.public_url,
      metadata = EXCLUDED.metadata,
      deleted_at = NULL
  RETURNING * INTO asset;
  PERFORM public.write_audit_log(
    'media.upload',
    'media',
    asset.id::TEXT,
    jsonb_build_object('file_name', asset.file_name, 'mime_type', asset.mime_type)
  );
  RETURN asset;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_delete_media(p_media_id UUID)
RETURNS BOOLEAN
SECURITY DEFINER
SET search_path = public, pg_temp
LANGUAGE plpgsql
AS $$
DECLARE
  asset public.media_assets;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Administrator access required' USING ERRCODE = '42501';
  END IF;
  UPDATE public.media_assets
  SET deleted_at = COALESCE(deleted_at, NOW())
  WHERE id = p_media_id
  RETURNING * INTO asset;
  IF asset.id IS NULL THEN
    RAISE EXCEPTION 'Media asset not found' USING ERRCODE = 'P0002';
  END IF;
  DELETE FROM storage.objects
  WHERE bucket_id = asset.storage_bucket AND name = asset.storage_path;
  PERFORM public.write_audit_log('media.delete', 'media', p_media_id::TEXT,
    jsonb_build_object('storage_path', asset.storage_path));
  RETURN TRUE;
END;
$$;

CREATE OR REPLACE FUNCTION public.mark_notification_read(p_notification_id UUID)
RETURNS BOOLEAN
SECURITY DEFINER
SET search_path = public, pg_temp
LANGUAGE sql
AS $$
  UPDATE public.notifications
  SET read_at = COALESCE(read_at, NOW())
  WHERE id = p_notification_id AND recipient_id = auth.uid()
  RETURNING TRUE;
$$;


-- ④ 权限补全
GRANT EXECUTE ON FUNCTION public.get_my_profile() TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.try_claim_primary_superadmin() TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.has_any_role(TEXT[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_dashboard_stats() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_list_users() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_list_comments(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_list_reports(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_list_content(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_list_media() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_list_audit_logs(INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION public.moderate_comment(BIGINT, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.report_comment(BIGINT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_update_account_status(UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.superadmin_update_role(UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.register_media_asset(TEXT, TEXT, TEXT, BIGINT, TEXT, JSONB) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_delete_media(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mark_notification_read(UUID) TO authenticated;
